- CODE_OF_CONDUCT.md
- README.md
- example/example.md
Signed-off-by: Luke Hinds <lhinds@redhat.com>
> Add an example template

- README.md
Replace a stray instance of Tekton
> Tekton -> sigstore

- FluxCD/README.md
Adding Flux family of projects to Sigstore friends.
Thanks Sigstore team for cosign, it's an awesome project!
> Add Flux project

- VMware/README.md
VMware is a friend of sigstore
> VMware supports sigstore

- Smallstep/README.md
> Add smallstep as a friend

- Red Hat/README.md
Signed-off-by: Daniel Messer <dmesser@redhat.com>
> add redhat as a friend

- Kyverno/README.md
Signed-off-by: Jim Bugwadia <jim@nirmata.com>
Add Kyverno
> add a friend - Kyverno!

- GoReleaser/README.md
added goreleaser to the friend list
n/a
n/a
> added goreleaser

- README.md
Signed-off-by: Ville Aikas <vaikas@chainguard.dev>
Add a direct link to example/example.md
Fixes
```release-note
```
> Add actual link to example/example.md file

- minectl/README.md
Add minectl to the list of friends
> feat: add minectl to friends list

- chainguard/README.md
Add Chainguard as a friendly friend of sigstore.
Signed-off-by: Ville Aikas <vaikas@chainguard.dev>
> Add Chainguard as friends of sigstore.

- helm/README.md
Added Helm as a friend of the sigstore project
> Added Helm

- Connaisseur/README.md
> add a friend - Connaisseur!

- archlinux/README.md
> Add Arch Linux

- VMware/README.md
Signed-off-by: hectorj2f <hectorf@vmware.com>
Add a new product to the list of VMware products using sigstore tools
Fixes
```release-note
```
> friends: add TAP to the list of VMware products using sigstore tools

- Amazon/README.md
Adding Amazon to the friends. from https://twitter.com/lorenc_dan/status/1483576185196093441?s=20
> Add Amazon readme

- JReleaser/README.md
Add JReleaser to the friend list
N/A
N/A
> Add JReleaser

- JReleaser/README.md
Fix typos in JReleaser description
N/A
N/A
> Fix typos in JReleaser description

- Google/README.md
Adding a modest callout to Google's involvement in Sigstore, for now. Will update with adoption by other teams over time.
```release-note
NONE
```
> Add Google

- Amazon/README.md
Improve accuracy of Amazon friends listing
> Update Amazon readme

- tekton/README.md
Signed-off-by: Priya Wadhwa <priya@chainguard.dev>
> Add tekton to friends repo

- Authzed/README.md
> Authzed: init

- SUSE/README.md
> SUSE readme added

- ocicl/README.md
> Mention ocicl
